---
- name: ansible playbook to copy a file
  hosts: all
  become: true
  tasks:
  - name: copy file
    copy:
      src: /opt/ansible/index.html
      dest: /home/ansadmin
      mode: 0600
      owner: anisha

