---
- name: this playbook is to create users.
  hosts: all
  become: true
    #vars:
    #user: john
  vars_files:
    - user.yml
  tasks:
  - name: creating user {{ user }}
    user: 
      name: "{{ user }}"
