---
- name: this playbook installs packages
  hosts: webservers
  become: true
  tasks:
  - name: this installs packages
    yum:
      # name: ['git','make','gcc','wget','telnet','gzip']
      name: "{{item}}"
      state: installed
    with_items:
      - git
      - make
      - gcc
      - wget
      - telnet
      - gzip
