---
- name: setup tomcat
  hosts: all
  become: true
  tasks:
  - name: install java on RedHat OS
    yum:
      name: java
      state: installed
    when: ansible_os_family == "RedHat"

  - name: install java on ubuntu
    apt:
      name: default-jdk
      state: present
    when: ansible_os_family == "Debian"

  - name: download tomcat packages
    get_url:
      url: https://dlcdn.apache.org/tomcat/tomcat-11/v11.0.0-M4/bin/apache-tomcat-11.0.0-M4.tar.gz
      dest: /opt

  - name: untar apache
    unarchive:
      src: /opt/apache-tomcat-11.0.0-M4.tar.gz
      dest: /opt
      remote_src: yes
  
  - name:  execution permission for startup.sh file
    file:
      path: /opt/apache-tomcat-11.0.0-M4/bin/startup.sh
      mode: 0777

  - name: start tomcat services
    shell: nohup ./startup.sh
    args:
      chdir: /opt/apache-tomcat-11.0.0-M4/bin


