---
- name: this playbook uninstalls and starts httpd
  hosts: all
  become: true
  tasks:
  - name: this stops service of httpd
    service:
      name: httpd
      state: stopped
    when: ansible_os_family == "RedHat"

  - name: this uninstalls httpd
    yum:
      name: httpd
      state: removed
    when: ansible_os_family == "RedHat"

  - name: stop apache2
    service:
      name: apache2
      state: stopped
    when: ansible_os_family == "Debian"

  - name: uninstall apache2
    apt:
      name: apache2
      state: absent
    when: ansible_os_family == "Debian"
